// ===== 英語（外国語）のコンテンツ =====
// 日本の小学生向け。学習指導要領では3・4年で外国語活動、5・6年で教科としての外国語。
// そのため grade 3 から出題し、3・4年は身近な単語中心、5・6年で文や表現を扱う。
//
// word: 英語 / ja: 日本語の意味 / grade: 出題を始める学年

const EN_WORDS = [
  // 3年：身のまわりのもの・色・数
  { grade: 3, word: "apple", ja: "りんご" },
  { grade: 3, word: "dog", ja: "いぬ" },
  { grade: 3, word: "cat", ja: "ねこ" },
  { grade: 3, word: "book", ja: "ほん" },
  { grade: 3, word: "red", ja: "あか" },
  { grade: 3, word: "blue", ja: "あお" },
  { grade: 3, word: "green", ja: "みどり" },
  { grade: 3, word: "yellow", ja: "きいろ" },
  { grade: 3, word: "one", ja: "1" },
  { grade: 3, word: "two", ja: "2" },
  { grade: 3, word: "three", ja: "3" },
  { grade: 3, word: "school", ja: "がっこう" },
  { grade: 3, word: "pencil", ja: "えんぴつ" },
  { grade: 3, word: "bag", ja: "かばん" },
  { grade: 3, word: "water", ja: "みず" },
  { grade: 3, word: "fish", ja: "さかな" },
  { grade: 3, word: "bird", ja: "とり" },
  { grade: 3, word: "tree", ja: "き" },
  { grade: 3, word: "sun", ja: "たいよう" },
  { grade: 3, word: "rain", ja: "あめ" },

  // 4年：曜日・食べ物・動作
  { grade: 4, word: "Monday", ja: "月よう日" },
  { grade: 4, word: "Sunday", ja: "日よう日" },
  { grade: 4, word: "breakfast", ja: "朝ごはん" },
  { grade: 4, word: "lunch", ja: "昼ごはん" },
  { grade: 4, word: "dinner", ja: "夕ごはん" },
  { grade: 4, word: "run", ja: "走る" },
  { grade: 4, word: "swim", ja: "泳ぐ" },
  { grade: 4, word: "read", ja: "読む" },
  { grade: 4, word: "write", ja: "書く" },
  { grade: 4, word: "eat", ja: "食べる" },
  { grade: 4, word: "spring", ja: "春" },
  { grade: 4, word: "summer", ja: "夏" },
  { grade: 4, word: "autumn", ja: "秋" },
  { grade: 4, word: "winter", ja: "冬" },
  { grade: 4, word: "morning", ja: "朝" },
  { grade: 4, word: "night", ja: "夜" },
  { grade: 4, word: "friend", ja: "友だち" },
  { grade: 4, word: "family", ja: "家族" },
  { grade: 4, word: "teacher", ja: "先生" },
  { grade: 4, word: "music", ja: "音楽" },
  { grade: 4, word: "milk", ja: "ぎゅうにゅう" },
  { grade: 4, word: "rice", ja: "ごはん" },
  { grade: 4, word: "egg", ja: "たまご" },
  { grade: 4, word: "notebook", ja: "ノート" },
  { grade: 4, word: "eraser", ja: "けしゴム" },
  { grade: 4, word: "jump", ja: "とぶ" },
  { grade: 4, word: "sing", ja: "うたう" },
  { grade: 4, word: "dance", ja: "おどる" },
  { grade: 4, word: "cook", ja: "りょうりする" },
  { grade: 4, word: "sleep", ja: "ねる" },

  // 5年：教科・場所・性質
  { grade: 5, word: "science", ja: "理科" },
  { grade: 5, word: "math", ja: "算数" },
  { grade: 5, word: "hospital", ja: "病院" },
  { grade: 5, word: "station", ja: "駅" },
  { grade: 5, word: "library", ja: "図書館" },
  { grade: 5, word: "park", ja: "公園" },
  { grade: 5, word: "country", ja: "国" },
  { grade: 5, word: "city", ja: "都市" },
  { grade: 5, word: "beautiful", ja: "美しい" },
  { grade: 5, word: "difficult", ja: "むずかしい" },
  { grade: 5, word: "important", ja: "大切な" },
  { grade: 5, word: "delicious", ja: "おいしい" },
  { grade: 5, word: "favorite", ja: "お気に入りの" },
  { grade: 5, word: "future", ja: "将来" },
  { grade: 5, word: "dream", ja: "ゆめ" },

  // 6年：抽象語・行事
  { grade: 6, word: "memory", ja: "思い出" },
  { grade: 6, word: "experience", ja: "経験" },
  { grade: 6, word: "environment", ja: "環境" },
  { grade: 6, word: "culture", ja: "文化" },
  { grade: 6, word: "peace", ja: "平和" },
  { grade: 6, word: "festival", ja: "祭り" },
  { grade: 6, word: "graduation", ja: "卒業" },
  { grade: 6, word: "junior high school", ja: "中学校" },
  { grade: 6, word: "volunteer", ja: "ボランティア" },
  { grade: 6, word: "president", ja: "大統領" },
];

// あいさつ・やりとり。text の {} が空所。
const EN_PHRASES = [
  { grade: 3, text: "How are you? — I'm ___, thank you.", answer: "fine",
    options: ["fine", "eat", "book", "red"], ja: "げんきです、ありがとう" },
  { grade: 3, text: "___ morning!", answer: "Good",
    options: ["Good", "Many", "Very", "Some"], ja: "おはよう" },
  { grade: 3, text: "My ___ is Taro.", answer: "name",
    options: ["name", "color", "food", "book"], ja: "わたしの名前はタロウです" },
  { grade: 3, text: "Thank you. — You're ___.", answer: "welcome",
    options: ["welcome", "sorry", "happy", "ready"], ja: "どういたしまして" },
  { grade: 4, text: "___ do you like? — I like soccer.", answer: "What",
    options: ["What", "Who", "Where", "When"], ja: "何がすきですか" },
  { grade: 4, text: "___ is your birthday? — It's in May.", answer: "When",
    options: ["When", "What", "Who", "How"], ja: "たんじょう日はいつですか" },
  { grade: 4, text: "I ___ up at six.", answer: "get",
    options: ["get", "go", "make", "take"], ja: "6時に起きます" },
  { grade: 4, text: "___ is the library? — It's near the park.", answer: "Where",
    options: ["Where", "What", "Why", "Who"], ja: "図書館はどこですか" },
  { grade: 5, text: "I want ___ be a teacher.", answer: "to",
    options: ["to", "of", "in", "at"], ja: "先生になりたいです" },
  { grade: 5, text: "This is ___ favorite place.", answer: "my",
    options: ["my", "me", "I", "mine"], ja: "ここはわたしのお気に入りの場所です" },
  { grade: 5, text: "He ___ soccer every Sunday.", answer: "plays",
    options: ["plays", "play", "playing", "played"], ja: "彼は毎週日よう日にサッカーをします" },
  { grade: 5, text: "___ much is this? — It's 500 yen.", answer: "How",
    options: ["How", "What", "Who", "Where"], ja: "これはいくらですか" },
  { grade: 5, text: "Can you ___ me your pen?", answer: "lend",
    options: ["lend", "borrow", "buy", "give up"], ja: "ペンを貸してくれる？" },
  { grade: 5, text: "I usually ___ breakfast at seven.", answer: "have",
    options: ["have", "has", "having", "had"], ja: "たいてい7時に朝食を食べます" },
  { grade: 5, text: "___ do you go to school? — By bus.", answer: "How",
    options: ["How", "What", "When", "Why"], ja: "どうやって学校に行きますか" },
  { grade: 5, text: "She is good ___ playing the piano.", answer: "at",
    options: ["at", "in", "on", "for"], ja: "彼女はピアノをひくのが得意です" },
  { grade: 5, text: "There ___ two cats under the table.", answer: "are",
    options: ["are", "is", "am", "be"], ja: "テーブルの下にねこが2ひきいます" },
  { grade: 6, text: "I ___ to Kyoto last summer.", answer: "went",
    options: ["went", "go", "going", "goes"], ja: "去年の夏、京都に行きました" },
  { grade: 6, text: "My best ___ is the school festival.", answer: "memory",
    options: ["memory", "morning", "market", "minute"], ja: "一番の思い出は学園祭です" },
  { grade: 6, text: "I want to ___ the environment.", answer: "protect",
    options: ["protect", "produce", "prepare", "present"], ja: "環境を守りたいです" },
  { grade: 6, text: "We ___ enjoyed the trip.", answer: "all",
    options: ["all", "every", "each", "both"], ja: "わたしたちはみんな旅行を楽しみました" },
  { grade: 6, text: "This book is ___ than that one.", answer: "more interesting",
    options: ["more interesting", "interesting", "most interesting", "interestinger"], ja: "この本はあの本より面白いです" },
  { grade: 6, text: "If it ___ tomorrow, we will stay home.", answer: "rains",
    options: ["rains", "rain", "rained", "raining"], ja: "もし明日雨が降ったら、家にいます" },
  { grade: 6, text: "I have ___ finished my homework.", answer: "already",
    options: ["already", "yet", "ever", "still"], ja: "もう宿題を終わらせました" },
  { grade: 6, text: "This is the book ___ I read last week.", answer: "that",
    options: ["that", "who", "what", "where"], ja: "これは先週読んだ本です" },
  { grade: 3, text: "Nice to ___ you.", answer: "meet",
    options: ["meet", "make", "read", "open"], ja: "はじめまして" },
  { grade: 3, text: "___ you like apples? — Yes, I do.", answer: "Do",
    options: ["Do", "Is", "Are", "Am"], ja: "りんごはすきですか" },
  { grade: 3, text: "See ___ tomorrow!", answer: "you",
    options: ["you", "me", "it", "we"], ja: "また明日" },
  { grade: 3, text: "Let's ___ soccer.", answer: "play",
    options: ["play", "eat", "read", "open"], ja: "サッカーをしよう" },
  { grade: 3, text: "___ is this? — It's a cat.", answer: "What",
    options: ["What", "Who", "When", "Where"], ja: "これは何ですか" },
  { grade: 3, text: "Here you ___.", answer: "are",
    options: ["are", "is", "am", "be"], ja: "はい、どうぞ" },
  { grade: 4, text: "___ old are you? — I'm ten.", answer: "How",
    options: ["How", "What", "Who", "Why"], ja: "何さいですか" },
  { grade: 4, text: "I go to school ___ bike.", answer: "by",
    options: ["by", "in", "on", "to"], ja: "自転車で学校に行きます" },
  { grade: 4, text: "She ___ a red bag.", answer: "has",
    options: ["has", "have", "having", "is"], ja: "彼女は赤いかばんを持っています" },
  { grade: 3, text: "I ___ a red pen.", answer: "have",
    options: ["have", "has", "is", "am"], ja: "赤いペンを持っています" },
  { grade: 3, text: "This ___ my dog.", answer: "is",
    options: ["is", "am", "are", "be"], ja: "これはわたしの犬です" },
  { grade: 3, text: "I ___ blue.", answer: "like",
    options: ["like", "likes", "liking", "liked"], ja: "青がすきです" },
  { grade: 3, text: "___ birthday!", answer: "Happy",
    options: ["Happy", "Good", "Nice", "Great"], ja: "たんじょう日おめでとう" },
  { grade: 3, text: "___ is the bag?", answer: "Where",
    options: ["Where", "What", "Who", "When"], ja: "かばんはどこですか" },
  { grade: 3, text: "I ___ swim.", answer: "can",
    options: ["can", "do", "am", "is"], ja: "わたしは泳げます" },
  { grade: 4, text: "I ___ a new bike.", answer: "want",
    options: ["want", "wants", "wanting", "wanted"], ja: "新しい自転車がほしいです" },
  { grade: 4, text: "She ___ my sister.", answer: "is",
    options: ["is", "are", "am", "be"], ja: "彼女はわたしの姉（妹）です" },
  { grade: 4, text: "I ___ like natto.", answer: "don't",
    options: ["don't", "isn't", "doesn't", "can't"], ja: "わたしは納豆がすきではありません" },
  { grade: 4, text: "___ go to the park.", answer: "Let's",
    options: ["Let's", "Let", "Lets", "Letting"], ja: "公園に行こう" },
  { grade: 4, text: "He ___ run fast.", answer: "can",
    options: ["can", "cans", "canning", "could"], ja: "彼は速く走ることができます" },
  { grade: 4, text: "___ time is it?", answer: "What",
    options: ["What", "When", "Where", "Why"], ja: "何時ですか" },
  { grade: 3, text: "___ afternoon!", answer: "Good",
    options: ["Good", "Nice", "Fine", "Well"], ja: "こんにちは（午後のあいさつ）" },
  { grade: 3, text: "Good ___! See you tomorrow.", answer: "night",
    options: ["night", "day", "time", "week"], ja: "おやすみなさい" },
  { grade: 3, text: "___ you! — You're welcome.", answer: "Thank",
    options: ["Thank", "Think", "Take", "Talk"], ja: "ありがとう" },
  { grade: 3, text: "I'm ___. — That's OK.", answer: "sorry",
    options: ["sorry", "sunny", "story", "start"], ja: "ごめんなさい" },
  { grade: 3, text: "I am ___ now.", answer: "hungry",
    options: ["hungry", "hungrily", "hunger", "hungering"], ja: "わたしは今おなかがすいています" },
  { grade: 3, text: "___ you later!", answer: "See",
    options: ["See", "Sit", "Say", "Set"], ja: "またあとでね" },
  { grade: 3, text: "How ___ you? — I'm eight.", answer: "old",
    options: ["old", "many", "long", "far"], ja: "何さいですか" },
  { grade: 3, text: "___ is this? — It's a pen.", answer: "What",
    options: ["What", "Who", "Where", "When"], ja: "これは何ですか" },
  { grade: 3, text: "___ this a cat? — Yes, it is.", answer: "Is",
    options: ["Is", "Are", "Am", "Do"], ja: "これはねこですか" },
  { grade: 3, text: "I ___ a dog.", answer: "have",
    options: ["have", "has", "having", "haves"], ja: "わたしは犬をかっています" },
  { grade: 3, text: "___ color do you like? — I like blue.", answer: "What",
    options: ["What", "Who", "How", "Why"], ja: "何色がすきですか" },
  { grade: 3, text: "I like ___. They are sweet.", answer: "apples",
    options: ["apples", "apple's", "appling", "appled"], ja: "わたしはりんごがすきです" },
  { grade: 3, text: "Do you like milk? — Yes, I ___.", answer: "do",
    options: ["do", "am", "is", "does"], ja: "はい、すきです" },
  { grade: 3, text: "___ is a book on the desk.", answer: "There",
    options: ["There", "Their", "They", "These"], ja: "つくえの上に本があります" },
  { grade: 3, text: "Please ___ down.", answer: "sit",
    options: ["sit", "set", "seat", "site"], ja: "すわってください" },
  { grade: 3, text: "___ up, please.", answer: "Stand",
    options: ["Stand", "Sand", "Send", "Spend"], ja: "立ってください" },
  { grade: 3, text: "___ me, please.", answer: "Help",
    options: ["Help", "Hold", "Hope", "Heap"], ja: "手伝ってください" },
  { grade: 3, text: "Open your ___, please.", answer: "book",
    options: ["book", "cook", "look", "took"], ja: "本を開いてください" },
  { grade: 3, text: "How many ___ do you have? — Three.", answer: "pens",
    options: ["pens", "pen", "pen's", "pening"], ja: "ペンを何本もっていますか" },
  { grade: 3, text: "It's a ___ day today.", answer: "sunny",
    options: ["sunny", "sun", "suns", "sunning"], ja: "今日は晴れです" },
  { grade: 3, text: "___ is the weather? — It's rainy.", answer: "How",
    options: ["How", "What", "Who", "Where"], ja: "天気はどうですか" },
  { grade: 3, text: "I'm ___ Japan.", answer: "from",
    options: ["from", "for", "at", "of"], ja: "わたしは日本の出身です" },
  { grade: 3, text: "___ name is Ken.", answer: "His",
    options: ["His", "He", "Him", "He's"], ja: "彼の名前はケンです" },
  { grade: 3, text: "This is ___ pencil.", answer: "my",
    options: ["my", "me", "I", "mine"], ja: "これはわたしのえんぴつです" },
  { grade: 3, text: "___ you ready? — Yes, I am.", answer: "Are",
    options: ["Are", "Is", "Do", "Am"], ja: "じゅんびはいいですか" },
  { grade: 3, text: "Let's ___ together.", answer: "sing",
    options: ["sing", "sings", "sang", "singing"], ja: "いっしょに歌おう" },
  { grade: 3, text: "I ___ soccer every day.", answer: "play",
    options: ["play", "plays", "played", "playing"], ja: "わたしは毎日サッカーをします" },
  { grade: 3, text: "___ me, where is the station?", answer: "Excuse",
    options: ["Excuse", "Exit", "Expect", "Explain"], ja: "すみません、駅はどこですか" },
  { grade: 3, text: "Happy ___! — Thank you.", answer: "birthday",
    options: ["birthday", "birdday", "borrowday", "bathday"], ja: "たんじょう日おめでとう" },
  { grade: 3, text: "___ is my friend, Yuki.", answer: "This",
    options: ["This", "These", "Those", "Them"], ja: "こちらは友だちのユキです" },
  { grade: 3, text: "I ___ hungry.", answer: "am",
    options: ["am", "is", "are", "be"], ja: "わたしはおなかがすいています" },
  { grade: 3, text: "The cat is ___ the box.", answer: "in",
    options: ["in", "if", "is", "it"], ja: "ねこは箱の中にいます" },
  { grade: 3, text: "Look ___ the blackboard, please.", answer: "at",
    options: ["at", "of", "to", "by"], ja: "黒板を見てください" },
  { grade: 3, text: "___ you speak Japanese? — Yes, a little.", answer: "Can",
    options: ["Can", "Are", "Is", "Am"], ja: "日本語を話せますか" },
  { grade: 4, text: "___ is that girl? — She's my sister.", answer: "Who",
    options: ["Who", "What", "Where", "How"], ja: "あの女の子はだれですか" },
  { grade: 4, text: "I ___ to school by bike.", answer: "go",
    options: ["go", "goes", "going", "went"], ja: "自転車で学校に行きます" },
  { grade: 4, text: "___ do you get up? — At six thirty.", answer: "When",
    options: ["When", "Where", "Who", "Which"], ja: "いつ起きますか" },
  { grade: 4, text: "___ one do you want, red or blue?", answer: "Which",
    options: ["Which", "What", "Who", "Whose"], ja: "どちらがほしいですか" },
  { grade: 4, text: "___ bag is this? — It's mine.", answer: "Whose",
    options: ["Whose", "Who", "Which", "What"], ja: "これはだれのかばんですか" },
  { grade: 4, text: "I go to school ___ Monday.", answer: "on",
    options: ["on", "in", "at", "of"], ja: "月曜日に学校へ行きます" },
  { grade: 4, text: "My birthday is ___ July.", answer: "in",
    options: ["in", "on", "at", "to"], ja: "たんじょう日は7月です" },
  { grade: 4, text: "School starts ___ eight thirty.", answer: "at",
    options: ["at", "in", "on", "for"], ja: "学校は8時半に始まります" },
  { grade: 4, text: "I ___ tennis after school.", answer: "play",
    options: ["play", "plays", "played", "playing"], ja: "放課後テニスをします" },
  { grade: 4, text: "She ___ to music every night.", answer: "listens",
    options: ["listens", "listen", "listening", "listened"], ja: "彼女は毎晩音楽を聞きます" },
  { grade: 4, text: "He ___ have a bike.", answer: "doesn't",
    options: ["doesn't", "don't", "isn't", "aren't"], ja: "彼は自転車をもっていません" },
  { grade: 4, text: "___ she like cats? — Yes, she does.", answer: "Does",
    options: ["Does", "Do", "Is", "Are"], ja: "彼女はねこがすきですか" },
  { grade: 4, text: "I can ___ the piano.", answer: "play",
    options: ["play", "plays", "played", "playing"], ja: "わたしはピアノをひけます" },
  { grade: 4, text: "I ___ swim well.", answer: "can't",
    options: ["can't", "don't", "isn't", "am not"], ja: "わたしはうまく泳げません" },
  { grade: 4, text: "___ I use your pen? — Sure.", answer: "Can",
    options: ["Can", "Am", "Is", "Do"], ja: "ペンを使ってもいいですか" },
  { grade: 4, text: "How ___ is this cap? — Five dollars.", answer: "much",
    options: ["much", "many", "long", "old"], ja: "このぼうしはいくらですか" },
  { grade: 4, text: "How ___ students are there? — Twenty.", answer: "many",
    options: ["many", "much", "long", "far"], ja: "生徒は何人いますか" },
  { grade: 4, text: "There ___ two dogs in the park.", answer: "are",
    options: ["are", "is", "am", "be"], ja: "公園に犬が2ひきいます" },
  { grade: 4, text: "The ball is ___ the desk.", answer: "under",
    options: ["under", "over", "into", "onto"], ja: "ボールはつくえの下にあります" },
  { grade: 4, text: "My house is ___ to the school.", answer: "next",
    options: ["next", "near by", "far", "beside of"], ja: "わたしの家は学校のとなりです" },
  { grade: 4, text: "Turn ___ at the corner.", answer: "right",
    options: ["right", "write", "rice", "ride"], ja: "角を右に曲がってください" },
  { grade: 4, text: "Go ___ this street.", answer: "along",
    options: ["along", "alone", "aloud", "already"], ja: "この道にそって進んでください" },
  { grade: 4, text: "___ the third floor, please.", answer: "To",
    options: ["To", "At", "In", "On"], ja: "3階までお願いします" },
  { grade: 4, text: "What ___ do you like? — I like summer.", answer: "season",
    options: ["season", "reason", "season's", "seasons'"], ja: "どの季節がすきですか" },
  { grade: 4, text: "What ___ is it today? — It's Friday.", answer: "day",
    options: ["day", "date", "time", "week"], ja: "今日は何曜日ですか" },
  { grade: 4, text: "I want ___ apple, please.", answer: "an",
    options: ["an", "a", "the", "of"], ja: "りんごを1つください" },
  { grade: 4, text: "I have ___ homework today.", answer: "some",
    options: ["some", "many", "a few", "few"], ja: "今日は宿題があります" },
  { grade: 4, text: "___ are my shoes.", answer: "These",
    options: ["These", "This", "That", "It"], ja: "これらはわたしのくつです" },
  { grade: 4, text: "Don't ___ in the library.", answer: "run",
    options: ["run", "runs", "ran", "running"], ja: "図書館では走らないで" },
  { grade: 4, text: "Let's ___ lunch together.", answer: "have",
    options: ["have", "has", "had", "having"], ja: "いっしょにお昼を食べよう" },
  { grade: 4, text: "I like dogs ___ cats.", answer: "and",
    options: ["and", "but", "or", "so"], ja: "犬もねこもすきです" },
  { grade: 4, text: "I like tea, ___ I don't like coffee.", answer: "but",
    options: ["but", "and", "so", "if"], ja: "お茶はすきですが、コーヒーはすきではありません" },
  { grade: 4, text: "It's cold, ___ close the window.", answer: "so",
    options: ["so", "but", "or", "if"], ja: "寒いので、窓を閉めましょう" },
  { grade: 4, text: "She is ___ TV now.", answer: "watching",
    options: ["watching", "watch", "watches", "watched"], ja: "彼女は今テレビを見ています" },
  { grade: 4, text: "They ___ playing in the yard.", answer: "are",
    options: ["are", "is", "am", "be"], ja: "彼らは庭で遊んでいます" },
  { grade: 4, text: "___ you help me? — Sure.", answer: "Can",
    options: ["Can", "Are", "Do you can", "Is"], ja: "手伝ってくれますか" },
  { grade: 4, text: "This is ___ book, not yours.", answer: "her",
    options: ["her", "she", "hers of", "she's"], ja: "これは彼女の本で、あなたのではありません" },
  { grade: 4, text: "Where ___ your parents? — They're at home.", answer: "are",
    options: ["are", "is", "am", "be"], ja: "ご両親はどこですか" },
  { grade: 4, text: "What ___ do you want to be? — A doctor.", answer: "job",
    options: ["job", "work", "thing", "place"], ja: "何の仕事につきたいですか" },
  { grade: 5, text: "I ___ to Kyoto last year.", answer: "went",
    options: ["went", "go", "goes", "going"], ja: "去年京都に行きました" },
  { grade: 5, text: "I ___ soccer yesterday.", answer: "played",
    options: ["played", "play", "plays", "playing"], ja: "きのうサッカーをしました" },
  { grade: 5, text: "It ___ fun.", answer: "was",
    options: ["was", "is", "were", "be"], ja: "楽しかったです" },
  { grade: 5, text: "We ___ happy to see you.", answer: "were",
    options: ["were", "was", "are", "be"], ja: "あなたに会えてうれしかったです" },
  { grade: 5, text: "I ___ eat natto, but now I like it.", answer: "didn't",
    options: ["didn't", "don't", "wasn't", "haven't"], ja: "昔は納豆を食べませんでしたが、今はすきです" },
  { grade: 5, text: "I'm going ___ study English tonight.", answer: "to",
    options: ["to", "for", "at", "of"], ja: "今夜英語を勉強するつもりです" },
  { grade: 5, text: "I ___ like some water, please.", answer: "would",
    options: ["would", "will", "am", "do"], ja: "お水をいただけますか" },
  { grade: 5, text: "This cake is ___ than that one.", answer: "sweeter",
    options: ["sweeter", "sweet", "sweetest", "more sweet"], ja: "このケーキはあれよりあまいです" },
  { grade: 5, text: "Ken runs ___ fast as Yuki.", answer: "as",
    options: ["as", "so", "too", "very"], ja: "ケンはユキと同じくらい速く走ります" },
  { grade: 5, text: "I like winter ___ I can ski.", answer: "because",
    options: ["because", "but", "or", "so that"], ja: "スキーができるので冬がすきです" },
  { grade: 5, text: "I visited my grandmother ___ Sunday.", answer: "last",
    options: ["last", "next", "this coming", "tomorrow"], ja: "先週の日曜日に祖母をたずねました" },
  { grade: 5, text: "My birthday is the ___ of May.", answer: "third",
    options: ["third", "three", "threeth", "thirdth"], ja: "たんじょう日は5月3日です" },
  { grade: 5, text: "I want to visit Australia ___ I like animals.", answer: "because",
    options: ["because", "but", "though", "until"], ja: "動物がすきなのでオーストラリアに行きたいです" },
  { grade: 5, text: "She is good ___ cooking.", answer: "at",
    options: ["at", "in", "on", "of"], ja: "彼女は料理が得意です" },
  { grade: 5, text: "How ___ is the tower? — About 300 meters.", answer: "tall",
    options: ["tall", "long", "much", "many"], ja: "そのタワーはどのくらいの高さですか" },
  { grade: 5, text: "___ you like some tea? — Yes, please.", answer: "Would",
    options: ["Would", "Are", "Do", "Can"], ja: "お茶はいかがですか" },
  { grade: 5, text: "I'd like to ___ a table for two.", answer: "book",
    options: ["book", "take", "make up", "put"], ja: "2名で席を予約したいです" },
  { grade: 5, text: "Can you tell me ___ to get to the museum?", answer: "how",
    options: ["how", "what", "who", "which"], ja: "博物館への行き方を教えてもらえますか" },
  { grade: 5, text: "I enjoyed ___ with my friends.", answer: "talking",
    options: ["talking", "talk", "talked", "to talk"], ja: "友だちと話すのを楽しみました" },
  { grade: 5, text: "My dream is to ___ a vet.", answer: "become",
    options: ["become", "becomes", "becoming", "became"], ja: "わたしの夢はじゅう医になることです" },
  { grade: 5, text: "There ___ many people at the festival.", answer: "were",
    options: ["were", "was", "are", "is"], ja: "祭りにはたくさんの人がいました" },
  { grade: 6, text: "This is the ___ movie I have ever seen.", answer: "best",
    options: ["best", "good", "better", "more good"], ja: "これは今まで見た中でいちばんよい映画です" },
  { grade: 6, text: "Mt. Fuji is the ___ mountain in Japan.", answer: "highest",
    options: ["highest", "high", "higher", "more high"], ja: "富士山は日本でいちばん高い山です" },
  { grade: 6, text: "I have ___ been to Okinawa.", answer: "never",
    options: ["never", "ever", "yet", "already"], ja: "沖縄には行ったことがありません" },
  { grade: 6, text: "Have you ___ finished your homework? — Yes, I have.", answer: "already",
    options: ["already", "yet", "never", "ago"], ja: "もう宿題を終えましたか" },
  { grade: 6, text: "I ___ studying English for three years.", answer: "have been",
    options: ["have been", "am", "was", "had"], ja: "3年間英語を勉強しています" },
  { grade: 6, text: "The letter ___ written by my father.", answer: "was",
    options: ["was", "did", "has", "were"], ja: "その手紙は父によって書かれました" },
  { grade: 6, text: "English is ___ in many countries.", answer: "spoken",
    options: ["spoken", "speak", "speaking", "spoke"], ja: "英語は多くの国で話されています" },
  { grade: 6, text: "If you ___ hard, you will pass the test.", answer: "study",
    options: ["study", "studies", "studied", "studying"], ja: "一生けんめい勉強すれば、テストに合格するでしょう" },
  { grade: 6, text: "I think ___ this book is interesting.", answer: "that",
    options: ["that", "what", "which", "who"], ja: "この本はおもしろいと思います" },
  { grade: 6, text: "The boy ___ is running is my brother.", answer: "who",
    options: ["who", "which", "whose", "whom"], ja: "走っている男の子はわたしの兄弟です" },
  { grade: 6, text: "I want to be a teacher ___ help children.", answer: "to",
    options: ["to", "for", "so", "that"], ja: "子どもを助けるために先生になりたいです" },
  { grade: 6, text: "It is important ___ read books.", answer: "to",
    options: ["to", "for", "of", "at"], ja: "本を読むことは大切です" },
  { grade: 6, text: "I'm looking forward ___ seeing you.", answer: "to",
    options: ["to", "for", "at", "on"], ja: "お会いするのを楽しみにしています" },
  { grade: 6, text: "She asked me ___ I liked sushi.", answer: "if",
    options: ["if", "that", "so", "or"], ja: "彼女はわたしにすしがすきかたずねました" },
  { grade: 6, text: "My town is famous ___ its old temple.", answer: "for",
    options: ["for", "of", "at", "with"], ja: "わたしの町は古い寺で有名です" },
  { grade: 6, text: "We should ___ care of the environment.", answer: "take",
    options: ["take", "make", "do", "give"], ja: "わたしたちは環境を大切にすべきです" },
  { grade: 6, text: "You ___ not eat in the classroom.", answer: "must",
    options: ["must", "can", "will", "would"], ja: "教室で食べてはいけません" },
  { grade: 6, text: "I ___ to finish this report by Friday.", answer: "have",
    options: ["have", "must", "should", "can"], ja: "金曜日までにこの報告を終えなければなりません" },
  { grade: 6, text: "Could you ___ that again, please?", answer: "say",
    options: ["say", "tell", "speak", "talk"], ja: "もう一度言っていただけますか" },
  { grade: 6, text: "___ don't we go to the beach?", answer: "Why",
    options: ["Why", "How", "What", "When"], ja: "海に行きませんか" },
  { grade: 6, text: "I was ___ when I heard the news.", answer: "surprised",
    options: ["surprised", "surprising", "surprise", "surprises"], ja: "その知らせを聞いておどろきました" },
  { grade: 6, text: "Kyoto is worth ___.", answer: "visiting",
    options: ["visiting", "visit", "to visit", "visited"], ja: "京都はたずねる価値があります" },
];
